micronaut:
  application:
    name: nossaCasaDoCodigo

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/cdc
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123
    schema-generate: CREATE
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

logger:
  levels:
    io.micronaut.transactional: DEBUG